OPEN CV IMAGE READ PROGRAM

In [1]:
#program to load an color image in grayscale 
import numpy as np
import cv2


#cv2.imread() method loads an image from the specified file
img = cv2.imread('download.jpg')

#cv2.imshow() method is used to display an image in a window
cv2.imshow('image',img)

# Using 0 to read image in grayscale mode and  display it
img1 = cv2.imread('download.jpg',0)
cv2.imshow('g',img1)

#waitKey(0) will display the window infinitely until any keypress
cv2.waitKey(0)

#cv2.destroyAllWindows() simply destroys all the windows we created.
cv2.destroyAllWindows()
#(img.shape) returns a tuple of number of rows, columns 
#and channels (if image is color)
print(img.shape)
print(img1.shape)

print(img[:,:,0])

(183, 275, 3)
(183, 275)
[[194 195 197 ... 149 149 148]
 [196 197 199 ... 150 150 149]
 [199 200 202 ... 151 151 151]
 ...
 [ 48  47  46 ...  26  26  26]
 [ 46  46  44 ...  26  26  26]
 [ 44  44  42 ...  26  26  26]]
